# データベース接続設定
# spring.datasource.url=jdbc:mysql://localhost:3306/song_db?useSSL=false&serverTimezone=Asia/Tokyo
# spring.datasource.username=root
# spring.datasource.password=forte147

# JPA設定（テーブル自動生成）
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# UTF-8文字化け対策
# spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# spring.datasource.hikari.connection-init-sql=SET NAMES utf8mb4

# ユーザー認証設定
spring.security.user.name=admin
spring.security.user.password=forte147


# spring.datasource.url=jdbc:postgresql://db.orktdcdhymjrfuyhribg.supabase.co:5432/postgres
spring.datasource.url=jdbc:postgresql://aws-0-ap-northeast-1.pooler.supabase.com:6543/postgres?user=postgres.orktdcdhymjrfuyhribg&password=Motherbasis39Forte147
# spring.datasource.username=postgres
# spring.datasource.password=Motherbasis39Forte147
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.datasource.hikari.maximum-pool-size=1
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.leak-detection-threshold=5000
spring.datasource.hikari.pool-name=SupabaseHikariPool
spring.datasource.hikari.connection-test-query=SELECT 1

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.datasource.hikari.cachePrepStmts=true
spring.datasource.hikari.prepStmtCacheSize=250
spring.datasource.hikari.prepStmtCacheSqlLimit=2048
spring.datasource.hikari.useServerPrepStmts=true
spring.datasource.hikari.useLocalSessionState=true
spring.datasource.hikari.rewriteBatchedStatements=true
spring.datasource.hikari.cacheResultSetMetadata=true
spring.datasource.hikari.cacheServerConfiguration=true
spring.datasource.hikari.elideSetAutoCommits=true
spring.datasource.hikari.maintainTimeStats=false