name: Deploy Frontend to Vercel

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          cd frontend/my-next-app
          npm install --legacy-peer-deps

      - name: Build project (Next.js)
        run: |
          cd frontend/my-next-app
          npm run build

      - name: Install Vercel CLI
        run: npm install -g vercel@latest

      - name: Pull Vercel envs
        run: |
          cd frontend/my-next-app
          vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Prebuild with Vercel
        run: |
          vercel build --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy to Vercel (Prebuilt)
        run: |
          cd frontend/my-next-app
          vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}